version: '3.8'
services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: quarkus/banking-service-jvm
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/banking
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_LOG_CONSOLE_JSON: "true"
      QUARKUS_LOG_CONSOLE_ENABLE: "true"
    command: [ "java", "-jar", "/deployments/quarkus-run.jar" ]

volumes:
  postgres_data:
